//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Occf.Languages.Java.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Occf.Languages.Java.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] CoverageWriter_File {
            get {
                object obj = ResourceManager.GetObject("CoverageWriter_File", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CoverageWriter_UM {
            get {
                object obj = ResourceManager.GetObject("CoverageWriter_UM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] junit_4_8_2 {
            get {
                object obj = ResourceManager.GetObject("junit_4_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Occf_Writer_File_Java {
            get {
                object obj = ResourceManager.GetObject("Occf_Writer_File_Java", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Occf_Writer_UM_Java {
            get {
                object obj = ResourceManager.GetObject("Occf_Writer_UM_Java", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
