/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.ac.waseda.cs.washi;

public class CoverageWriterJNI {
  public final static native boolean WriteStatement(int jarg1, int jarg2, int jarg3);
  public final static native boolean WritePredicate(int jarg1, int jarg2, boolean jarg3);
}
